"""initial

Revision ID: a07f8fe369b2
Revises: 
Create Date: 2025-11-25 14:19:35.556331

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a07f8fe369b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.alter_column(
            'status',
            existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
            comment=None,
            existing_comment='Present/Absent/Late/Excused',
            existing_nullable=False,
        )
        batch_op.alter_column(
            'timestamp',
            existing_type=mysql.DATETIME(),
            nullable=True,
            existing_server_default=sa.text('CURRENT_TIMESTAMP'),
        )
        batch_op.alter_column(
            'source',
            existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
            comment=None,
            existing_comment='camera/upload/manual',
            existing_nullable=True,
        )
        batch_op.alter_column(
            'created_at',
            existing_type=mysql.DATETIME(),
            nullable=True,
            existing_server_default=sa.text('CURRENT_TIMESTAMP'),
        )
        # Only drop the index if it actually exists in MySQL to avoid errors.
        conn = op.get_bind()
        inspector = sa.inspect(conn)
        attendance_indexes = [idx['name'] for idx in inspector.get_indexes('attendance')]
        if 'idx_attendance_face_id' in attendance_indexes or batch_op.f('idx_attendance_face_id') in attendance_indexes:
            batch_op.drop_index(batch_op.f('idx_attendance_face_id'))
        # Skipping drop of 'idx_attendance_user_id' because it may be
        # required by existing foreign key constraints in MySQL.
        batch_op.create_foreign_key(None, 'faces', ['face_id'], ['face_id'])

    with op.batch_alter_table('faces', schema=None) as batch_op:
        batch_op.alter_column(
            'face_id',
            existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128),
            comment=None,
            existing_comment='Unique face identifier (UUID or DB id)',
            existing_nullable=False,
        )
        batch_op.alter_column(
            'image_path',
            existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=512),
            comment=None,
            existing_comment='Path or URL to stored image',
            existing_nullable=True,
        )
        batch_op.alter_column(
            'metadata',
            existing_type=mysql.JSON(),
            type_=sa.Text(),
            comment=None,
            existing_comment='Optional metadata (pose, quality, descriptors)',
            existing_nullable=True,
        )
        batch_op.alter_column(
            'enrolled_at',
            existing_type=mysql.DATETIME(),
            nullable=True,
            existing_server_default=sa.text('CURRENT_TIMESTAMP'),
        )
        # Skipping drop of 'idx_faces_user_id' because it may be
        # required by existing foreign key constraints in MySQL.

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.alter_column(
            'issued_at',
            existing_type=mysql.DATETIME(),
            nullable=True,
            existing_server_default=sa.text('CURRENT_TIMESTAMP'),
        )
        batch_op.alter_column(
            'revoked',
            existing_type=mysql.TINYINT(display_width=1),
            nullable=True,
            existing_server_default=sa.text("'0'"),
        )
        # Skipping drop of 'idx_refresh_user' because it may be
        # required by existing foreign key constraints in MySQL.

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column(
            'user_id',
            existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
            comment=None,
            existing_comment='Human-readable ID like EMP001',
            existing_nullable=True,
        )
        batch_op.alter_column(
            'created_at',
            existing_type=mysql.DATETIME(),
            nullable=True,
            existing_server_default=sa.text('CURRENT_TIMESTAMP'),
        )
        batch_op.alter_column(
            'updated_at',
            existing_type=mysql.DATETIME(),
            nullable=True,
            existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
        )
        # Only drop the index if it exists to avoid errors on MySQL.
        conn = op.get_bind()
        inspector = sa.inspect(conn)
        user_indexes = [idx['name'] for idx in inspector.get_indexes('users')]
        if 'uq_users_user_id' in user_indexes or batch_op.f('uq_users_user_id') in user_indexes:
            batch_op.drop_index(batch_op.f('uq_users_user_id'))
        batch_op.create_index(batch_op.f('ix_users_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_user_id'))
        batch_op.create_index(batch_op.f('uq_users_user_id'), ['user_id'], unique=True)
        batch_op.alter_column(
            'updated_at',
            existing_type=mysql.DATETIME(),
            nullable=False,
            existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
        )
        batch_op.alter_column(
            'created_at',
            existing_type=mysql.DATETIME(),
            nullable=False,
            existing_server_default=sa.text('CURRENT_TIMESTAMP'),
        )
        batch_op.alter_column(
            'user_id',
            existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
            comment='Human-readable ID like EMP001',
            existing_nullable=True,
        )

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        # Index 'idx_refresh_user' was left in place during upgrade; no-op here.
        batch_op.alter_column(
            'revoked',
            existing_type=mysql.TINYINT(display_width=1),
            nullable=False,
            existing_server_default=sa.text("'0'"),
        )
        batch_op.alter_column(
            'issued_at',
            existing_type=mysql.DATETIME(),
            nullable=False,
            existing_server_default=sa.text('CURRENT_TIMESTAMP'),
        )

    with op.batch_alter_table('faces', schema=None) as batch_op:
        # Index 'idx_faces_user_id' was left in place during upgrade; no-op here.
        batch_op.alter_column(
            'enrolled_at',
            existing_type=mysql.DATETIME(),
            nullable=False,
            existing_server_default=sa.text('CURRENT_TIMESTAMP'),
        )
        batch_op.alter_column(
            'metadata',
            existing_type=sa.Text(),
            type_=mysql.JSON(),
            comment='Optional metadata (pose, quality, descriptors)',
            existing_nullable=True,
        )
        batch_op.alter_column(
            'image_path',
            existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=512),
            comment='Path or URL to stored image',
            existing_nullable=True,
        )
        batch_op.alter_column(
            'face_id',
            existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128),
            comment='Unique face identifier (UUID or DB id)',
            existing_nullable=False,
        )

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        # Indexes on 'attendance' were left in place during upgrade; no-op here.
        batch_op.alter_column(
            'created_at',
            existing_type=mysql.DATETIME(),
            nullable=False,
            existing_server_default=sa.text('CURRENT_TIMESTAMP'),
        )
        batch_op.alter_column(
            'source',
            existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
            comment='camera/upload/manual',
            existing_nullable=True,
        )
        batch_op.alter_column(
            'timestamp',
            existing_type=mysql.DATETIME(),
            nullable=False,
            existing_server_default=sa.text('CURRENT_TIMESTAMP'),
        )
        batch_op.alter_column(
            'status',
            existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
            comment='Present/Absent/Late/Excused',
            existing_nullable=False,
        )

    # ### end Alembic commands ###
